// @ts-ignore-next-line
import * as fs from 'fs'
// @ts-ignore-next-line
import * as path from 'path'
// @ts-ignore-next-line
import { fileURLToPath } from 'url'
import { LstProps, RwaProps, TokenProps } from '../utils/types'

// @ts-ignore
const __dirname = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(__dirname, '../..')

export interface RawToken {
  chainId?: string | number
  address: string
  name?: string
  symbol?: string
  decimals?: number
  logoURI?: string
}

export interface LabelToken {
  chainId: string
  name: string
  symbol: string
  address: string
  decimals: number
  logoURI?: string
  tags: string[]
  props: TokenProps
}

export interface CandidateRow {
  chainId: string
  address: string
  symbol: string
  name: string
  rule: string
  rwa?: RwaProps
  lst?: LstProps
}

/** Read every top-level chain list (e.g. 1.json, 8453.json, fuel.json). */
export function readChainLists(): { chainId: string; tokens: RawToken[] }[] {
  const out: { chainId: string; tokens: RawToken[] }[] = []
  for (const file of fs.readdirSync(REPO_ROOT)) {
    if (!file.endsWith('.json')) continue
    if (file === 'omni-list.json') continue
    const base = file.replace('.json', '')
    if (!/^\d+$/.test(base) && base !== 'fuel') continue
    let data: any
    try {
      data = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, file), 'utf8'))
    } catch {
      continue
    }
    const list = data?.list
    if (!list || typeof list !== 'object') continue
    const tokens = Object.entries(list).map(([address, t]: [string, any]) => ({ ...t, address }))
    out.push({ chainId: String(data.chainId ?? base), tokens })
  }
  return out
}

/** Build a token entry for a label list (rwa.json / lst.json). */
export function toLabelToken(chainId: string, t: RawToken, props: TokenProps): LabelToken {
  return {
    chainId,
    name: t.name ?? '',
    symbol: t.symbol ?? '',
    address: (t.address ?? '').toLowerCase(),
    decimals: Number(t.decimals ?? 18),
    ...(t.logoURI ? { logoURI: t.logoURI } : {}),
    tags: [],
    props,
  }
}

/** Serialize an address registry to a `.generated.ts` module string. */
export function serializeRegistry<T>(
  constName: string,
  typeName: string,
  generatorCmd: string,
  reg: { [c: string]: { [a: string]: T } },
): string {
  const chainIds = Object.keys(reg).sort((a, b) => Number(a) - Number(b) || a.localeCompare(b))
  const body = chainIds
    .map((chainId) => {
      const addrs = Object.keys(reg[chainId]).sort()
      const entries = addrs.map((a) => `    '${a}': ${JSON.stringify(reg[chainId][a])},`).join('\n')
      return `  '${chainId}': {\n${entries}\n  },`
    })
    .join('\n')
  return (
    `// AUTO-GENERATED by \`${generatorCmd}\`. Do not edit by hand.\n` +
    `// Seeded from conservative auto-rules over the token lists. Curated overrides\n` +
    `// live in the sibling registry file and win over anything in here.\n` +
    `import { ${typeName} } from '../utils/types'\n\n` +
    `export const ${constName}: ${typeName} = {\n${body}\n}\n`
  )
}
