// @ts-ignore-next-line
import * as fs from 'fs'
// @ts-ignore-next-line
import * as path from 'path'
// @ts-ignore-next-line
import { fileURLToPath } from 'url'
import { meshGroupMap, meshSplits } from './mesh'

// @ts-ignore
const __dirname = path.dirname(fileURLToPath(import.meta.url))

/**
 * `npm run oft:mesh` — find the assets the generator split across groups by
 * following the OFT peer links in the published omni-list, and write the
 * reviewed unification to mesh-groups.json (read by the generator through
 * meshMap.ts). Accumulates: a deployment already unified by an earlier run is
 * kept (it now sits in the canonical group and would not show as a move), so
 * the file converges. `--check` writes nothing and exits 1 while an
 * unreviewed split remains — a new split is either added (re-run without it)
 * or excluded in mesh-exclude.json.
 */
const check = process.argv.includes('--check')
const omni = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../../omni-list.json'), 'utf-8'))
const exclude: Record<string, string> =
  JSON.parse(fs.readFileSync(path.resolve(__dirname, './mesh-exclude.json'), 'utf-8')).exclude ?? {}
const outFile = path.resolve(__dirname, './mesh-groups.json')
const prev: Record<string, Record<string, string>> = fs.existsSync(outFile)
  ? (JSON.parse(fs.readFileSync(outFile, 'utf-8')).groups ?? {})
  : {}

const splits = meshSplits(omni, exclude)
const open = splits.filter((s) => !s.excluded)
for (const s of splits) {
  const tag = s.excluded ? `EXCLUDED (${s.excluded})` : `→ ${s.canonical}`
  console.log(
    `${tag}  ${Object.entries(s.groups)
      .map(([g, c]) => `${g} [${c.join(',')}]`)
      .join(' | ')}`,
  )
}
const moves = open.reduce((a, s) => a + s.moves.length, 0)
console.log(`\n${splits.length} split meshes, ${splits.length - open.length} excluded, ${moves} deployments to move`)

if (check) {
  // @ts-ignore
  process.exit(open.length ? 1 : 0)
}

const next = meshGroupMap(open)
for (const [chain, m] of Object.entries(prev))
  for (const [addr, g] of Object.entries(m)) if (!next[chain]?.[addr]) (next[chain] ??= {})[addr] = g
const sorted = Object.fromEntries(
  Object.entries(next)
    .sort(([a], [b]) => Number(a) - Number(b))
    .map(([c, m]) => [c, Object.fromEntries(Object.entries(m).sort(([a], [b]) => a.localeCompare(b)))]),
)
fs.writeFileSync(
  outFile,
  JSON.stringify(
    {
      _readme:
        'Generated by `npm run oft:mesh` (oft/meshReport.ts) from the OFT peer links; reviewed through mesh-exclude.json. chainId -> address -> asset group.',
      groups: sorted,
    },
    null,
    2,
  ) + '\n',
)
console.log(`wrote ${Object.values(sorted).reduce((a, m) => a + Object.keys(m).length, 0)} rows to mesh-groups.json`)
